### ISSUE TITLE
Unable to createsuperuser before applying migrations

### ISSUE THREAD

**Issue by tuukkalai** [StarSovu/Cyber-Security#1]
```sh
$  python manage.py createsuperuser
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'polls' isn't unique. You may not be able to reverse all URLs in this namespace
```
Following the instructions errored after running `python manage.py createsuperuser`.

Running `python manage.py migrate` before creating the super user seems to fix the issue.

**Comment by StarSovu** [comment]
Hei
Kiitos viestistä! Sain itsekin tuon ilmoituksen useita kertoja projektin aikana, mutta ei siitä tuntunut olevan mitään haittaa.

________________________________
From: Tuukka Laitinen ***@***.***>
Sent: 06 August 2022 22:09
To: StarSovu/Cyber-Security ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StarSovu/Cyber-Security] Unable to createsuperuser before applying migrations (Issue #1)


$  python manage.py createsuperuser
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'polls' isn't unique. You may not be able to reverse all URLs in this namespace

Following the instructions errored after running python manage.py createsuperuser.

Running python manage.py migrate before creating the super user seems to fix the issue.
